_target_: text_recognizer.models.LitTransformer
max_output_len: 682
start_token: <s>
end_token: <e>
pad_token: <p>
mapping:
  _target_: text_recognizer.data.mappings.EmnistMapping
  extra_symbols: ["\n"]
