[tool.poetry]
name = "text-recognizer"
version = "0.1.0"
authors = ["aktersnurra <gustaf.rydholm@gmail.com>"]
description = "A text recognizer using best pratices in python and deep learning."
license = "MIT"
readme = "README.md"
homepage = "https://github.com/aktersnurra/text-recognizer"
repository = "https://github.com/aktersnurra/text-recognizer"
keywords = ["text recognizer, deep learning, pytorch"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
wandb = "^0.8.36"
flake8-annotations = "^2.1.0"
flake8-docstrings = "^1.5.0"
darglint = "^1.3.1"
desert = "^2020.1.6"
marshmallow = "^3.6.0"
sphinx-autodoc-typehints = "^1.10.3"
sphinx_rtd_theme = "^0.4.3"
boltons = "^20.1.0"
h5py = "^2.10.0"
toml = "^0.10.1"
torch = "^1.5.0"
torchvision = "^0.6.0"
torchsummary = "^1.5.1"
loguru = "^0.5.0"
matplotlib = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.9.0"
pytest-mock = "^3.1.0"
black = "^19.10b0"
flake8 = "^3.8.2"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.0"
flake8-bugbear = "^20.1.4"
flake8-import-order = "^0.18.1"
safety = "^1.9.0"
mypy = "^0.770"
pytype = {version = "^2020.5.13", python = "3.7"}
typeguard = "^2.7.1"
xdoctest = "^0.12.0"
sphinx = "^3.0.4"
jupyter = "^1.0.0"

[tool.coverage.report]
fail_under = 50
[tool.poetry.scripts]
download-emnist = "text_recognizer.datasets.emnist_dataset:download_emnist"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
