_target_: pytorch_lightning.Trainer
gradient_clip_val: 0.5
fast_dev_run: false
accelerator: gpu
devices: 1
precision: 16
max_epochs: 256
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
accumulate_grad_batches: 1
overfit_batches: 0
