_target_: text_recognizer.criterions.transducer.Transducer
preprocessor:
  _target_: text_recognizer.data.utils.iam_preprocessor.Preprocessor 
  num_features: 1000
  tokens: iamdb_1kwp_tokens_1000.txt
  lexicon: iamdb_1kwp_lex_1000.txt
  use_words: false
  prepend_wordsep: false
  special_tokens: [ "<s>", "<e>", "<p>", "\n" ]
ngram: 0
# transitions: 1kwp_prune_0_10_optblank.bin
blank: "optional"
allow_repeats: true
reduction: "none"
