_target_: text_recognizer.data.mappings.word_piece.WordPieceMapping
num_features: 1000
tokens: iamdb_1kwp_tokens_1000.txt
lexicon: iamdb_1kwp_lex_1000.txt
use_words: false
prepend_wordsep: false
special_tokens: [ <s>, <e>, <p> ]
extra_symbols: [ "\n" ]
