_target_: text_recognizer.data.iam_extended_paragraphs.IAMExtendedParagraphs
batch_size: 4
num_workers: 12
train_fraction: 0.8
pin_memory: false
transform: transform/paragraphs.yaml
test_transform: transform/paragraphs.yaml
