_target_: text_recognizer.data.iam_lines.IAMLines
batch_size: 8
num_workers: 12
train_fraction: 0.9
pin_memory: true
transform:
  _target_: text_recognizer.data.transforms.line.IamLinesStem
  augment: true
test_transform:
  _target_: text_recognizer.data.transforms.line.IamLinesStem
  augment: false
tokenizer:
  _target_: text_recognizer.data.tokenizer.Tokenizer
