_target_: text_recognizer.data.iam_extended_paragraphs.IAMExtendedParagraphs
batch_size: 4
num_workers: 12
train_fraction: 0.8
pin_memory: true
transform:
  _target_: text_recognizer.data.transforms.paragraph.ParagraphStem
  augment: true
test_transform:
  _target_: text_recognizer.data.transforms.paragraph.ParagraphStem
  augment: false
target_transform:
  _target_: text_recognizer.data.transforms.pad.Pad
  max_len: 682
  pad_index: 3
tokenizer:
  _target_: text_recognizer.data.tokenizer.Tokenizer
  extra_symbols: ["\n"]
