_target_: text_recognizer.data.iam_extended_paragraphs.IAMExtendedParagraphs
batch_size: 4
num_workers: 12
train_fraction: 0.8
pin_memory: true
transform: transform/paragraphs.yaml
test_transform: test_transform/paragraphs.yaml
target_transform: target_transform/pad.yaml
mapping:
  _target_: text_recognizer.data.mappings.EmnistMapping
  extra_symbols: ["\n"]
