to_tensor:
  _target_: torchvision.transforms.ToTensor

color_jitter:
  _target_: torchvision.transforms.ColorJitter
  brightness: [0.5, 1.0]

random_affine:
  _target_: torchvision.transforms.RandomAffine
  degrees: 3
  translate: [0.0, 0.05]
  scale: [0.4, 1.1]
  shear: [-40, 50]
  fill: 0
