barlow:
  _target_: text_recognizer.data.transforms.barlow.BarlowTransform
  prim:
    embed_crop:
      _target_: text_recognizer.data.transforms.embed_crop.EmbedCrop
      augment: true

    color_jitter:
      _target_: torchvision.transforms.ColorJitter
      brightness: [0.8, 1.6]

    random_affine:
      _target_: torchvision.transforms.RandomAffine
      degrees: 1
      shear: [-30, 20]
      interpolation: BILINEAR
      fill: 0

    to_tensor:
      _target_: torchvision.transforms.ToTensor

  bis:
    embed_crop:
      _target_: text_recognizer.data.transforms.embed_crop.EmbedCrop
      augment: true

    color_jitter:
      _target_: torchvision.transforms.ColorJitter
      brightness: [0.5, 1.4]

    random_affine:
      _target_: torchvision.transforms.RandomAffine
      degrees: 1.5
      shear: [-30, 20]
      interpolation: BILINEAR
      fill: 0

    to_tensor:
      _target_: torchvision.transforms.ToTensor
