# @package _group_
- type: ModelCheckpoint
  args:
      monitor: val_loss
      mode: min
      save_last: true
- type: LearningRateMonitor
  args:
      logging_interval: step
# - type: EarlyStopping
#   args:
#       monitor: val_loss
#       mode: min
#       patience: 10
