_target_: text_recognizer.networks.vqvae.decoder.Decoder
out_channels: 1 
hidden_dim: 32
channels_multipliers: [4, 2, 1]
dropout_rate: 0.0
activation: mish
use_norm: true
num_residuals: 4
residual_channels: 32
