_target_: text_recognizer.networks.quantizer.quantizer.VectorQuantizer
input_dim: 192
codebook:
  _target_: text_recognizer.networks.quantizer.codebook.CosineSimilarityCodebook
  dim: 16
  codebook_size: 2048
  kmeans_init: true
  kmeans_iters: 10
  decay: 0.8
  eps: 1.0e-5
  threshold_dead: 2
commitment: 1.0
