defaults:
  - encoder: vae_encoder
  - decoder: vae_decoder

_target_: text_recognizer.networks.vqvae.vqvae.VQVAE
quantizer:
  _target_: text_recognizer.networks.quantizer.quantizer.VectorQuantizer
  input_dim: 128
  codebook:
    _target_: text_recognizer.networks.quantizer.codebook.CosineSimilarityCodebook
    dim: 8
    codebook_size: 512
    kmeans_init: true
    kmeans_iters: 10
    decay: 0.8
    eps: 1.0e-5
    threshold_dead: 2
  commitment: 1.0
