defaults:
  - callbacks: wandb_ocr
  - criterion: label_smoothing
  - dataset: iam_extended_paragraphs
  - hydra: default
  - lr_scheduler: one_cycle
  - mapping: word_piece
  - model: lit_transformer
  - network: conv_transformer
  - optimizer: madgrad
  - trainer: default

seed: 4711
tune: false
train: true
test: true
logging: INFO
