defaults:
  - network: vqvae
  - criterion: mse
  - optimizer: madgrad
  - lr_scheduler: one_cycle
  - model: lit_vqvae
  - dataset: iam_extended_paragraphs
  - trainer: default
  - callbacks:
    - checkpoint
    - learning_rate_monitor

seed: 4711
wandb: false
tune: false
train: true
test: true
load_checkpoint: null 
logging: INFO
